apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness
  namespace: test
spec:
  containers:
  - name: liveness
    image: harbor.kubeimooc.com/library/liveness
    #每隔3s向容器探测，是否正常
    # startupProbe 则专门用于容器启动期间的健康检查
    startupProbe:
     httpGet:
      path: /started
      port: 8080
      httpHeaders:
       - name: Custom-Header
         value: Awesome
      scheme: HTTP
     failureThreshold: 3
     periodSeconds: 3
