apiVersion: v1
kind: Pod

metadata:
  name: busybox
  namespace: test
  labels:
    app: busybox

spec:
#  nodeName: node02
  containers:
    - name: busybox
      image: busybox
  affinity:
    # 硬亲和， 满足节点 标签有app =test
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: app
                operator: In
                values:
                  - test
